parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:        
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_pgsql'
                server_version: '10.6'
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8
                mapping_types:
                    hstore: string
                    jsonb: string
                    geometry: string
            etab_datos:
                # configure these for your database server
                driver: 'pdo_pgsql'
                server_version: '10.6'
                url: '%env(resolve:DATABASE_ETAB_DATOS_URL)%'
                charset: utf8
                mapping_types:
                    jsonb: string
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    SonataUserBundle: ~
                    FOSUserBundle: ~
            etab_datos:
                connection: etab_datos
                auto_mapping: false