fos_user:
    db_driver:        orm # can be orm or odm
    firewall_name:    main
    user_class:     App\Entity\User

    group:
        group_class:   App\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
        
    from_email:
        address:        etab@correo.com
        sender_name:    'SIIG - eTab :: Reseteo de clave'

    service:
        user_manager: sonata.user.orm.user_manager
        
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value
