knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/bin/wkhtmltopdf-amd64'
        options:    []
    #image:
        #enabled:    false
        #binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        #options:    []
