snc_redis:
# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: predis
#            alias: default
#            dsn: "%env(REDIS_URL)%"
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_URL)%/1"
            logging: true
            
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default          # the name of your entity_manager connection
            #document_manager: default        # the name of your document_manager connection
        result_cache:
            client: cache
            entity_manager: [default, read]  # you may specify multiple entity_managers
        query_cache:
            client: cache
            entity_manager: default