vich_uploader:
    db_driver: orm

    mappings:
        origene_datos_file:
            uri_prefix: /origenes
            upload_destination: '%kernel.project_dir%/public/uploads'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
