<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Sonata\UserBundle\Entity\BaseGroup as BaseGroup;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 *
 * @ORM\Entity
 * @ORM\Table(name="fos_user_group")
 */
class Group extends BaseGroup
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\ManyToMany(targetEntity="FichaTecnica", inversedBy="gruposUsuarios")    
     * @ORM\OrderBy({"nombre" = "ASC"})
     * @ORM\JoinTable(name="group_fichatecnica",
     *      inverseJoinColumns={@ORM\JoinColumn(name="fichatecnica_id", referencedColumnName="id")}
     *      )
     **/
    protected $indicadores;
    
    /**
     * @ORM\ManyToMany(targetEntity="GrupoIndicadores", inversedBy="grupos")
     * @ORM\OrderBy({"nombre" = "ASC"})
     * @ORM\JoinTable(name="group_grupoindicadores",
     *      inverseJoinColumns={@ORM\JoinColumn(name="grupoindicadores_id", referencedColumnName="id")}
     * )
     **/
    protected $salas;

    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
   
    /**
     * Constructor
     */
    public function __construct($name, $roles = array())
    {
        parent::__construct($name, $roles = array());
        $this->indicadores = new \Doctrine\Common\Collections\ArrayCollection();
        $this->salas = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add indicadores
     *
     * @param \App\Entity\FichaTecnica $indicadores
     * @return Group
     */
    public function addIndicadore(\App\Entity\FichaTecnica $indicadores)
    {
        $this->indicadores[] = $indicadores;
    
        return $this;
    }

    /**
     * Remove indicadores
     *
     * @param \App\Entity\FichaTecnica $indicadores
     */
    public function removeIndicadore(\App\Entity\FichaTecnica $indicadores)
    {
        $this->indicadores->removeElement($indicadores);
    }

    /**
     * Get indicadores
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getIndicadores()
    {
        return $this->indicadores;
    }

    /**
     * Add salas
     *
     * @param \App\Entity\GrupoIndicadores $salas
     * @return Group
     */
    public function addSala(\App\Entity\GrupoIndicadores $salas)
    {
        $this->salas[] = $salas;
    
        return $this;
    }

    /**
     * Remove salas
     *
     * @param \App\Entity\GrupoIndicadores $salas
     */
    public function removeSala(\App\Entity\GrupoIndicadores $salas)
    {
        $this->salas->removeElement($salas);
    }

    /**
     * Get salas
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSalas()
    {
        return $this->salas;
    }
}
