calidad_rest:
    type:     rest
    resource: '@CalidadBundle/Controller/TableroCalidadRESTController.php'

controller_tablero:
    resource: '@CalidadBundle/Controller/TableroCalidadController.php'
    type: annotation

controller_plan_mejora:
    resource: '@CalidadBundle/Controller/PlanMejoraController.php'
    type: annotation