<?php

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

use App\Entity\Social;
/**
 * BoletinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialRepository extends ServiceEntityRepository
{

    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Social::class);
    }
	public function getRuta($sala,$token)
    {							
		$stmt = $this->getEntityManager()
		->getConnection()
		->prepare("SELECT * FROM social s left join grupo_indicadores g on g.id=s.sala  where s.token='$token' and s.sala='$sala'");
		$stmt->execute();
		$result= $stmt->fetchAll();
		
		foreach($result as $res)
		{
            $tiempo=$this->duracion(\DateTime::createFromFormat('Y-m-d H:i:s',$res['creado']));
            
			if(stripos($tiempo, 'dia') && !$res['es_permanente'])
			{
				if(substr($tiempo,0,stripos($tiempo,' ')) > $res['tiempo_dias'])
				    return "Error";
			}
		}
		return $result;
	}
	
	public function duracion(\DateTime $dateTime)
    {
        $delta = time() - $dateTime->getTimestamp();
        if ($delta < 0)
            throw new \Exception("createdAgo is unable to handle dates in the future");

        $duration = "";
        if ($delta < 60)
        {
            // Segundos
            $time = $delta;
            $duration = $time . " segundo" . (($time > 1) ? "s" : "") ;
        }
        else if ($delta <= 3600)
        {
            // Minutos
            $time = floor($delta / 60);
            $duration = $time . " minuto" . (($time > 1) ? "s" : "") ;
        }
        else if ($delta <= 86400)
        {
            // Horas
            $time = floor($delta / 3600);
            $duration = $time . " hora" . (($time > 1) ? "s" : "") ;
        }
        else
        {
            // Días
            $time = floor($delta / 86400);
            $duration = $time . " dia" . (($time > 1) ? "s" : "") ;
        }

        return $duration;
    }
}