<?php

namespace App\Entity\MatrizChiapas;

/**
 * MatrizSeguimientoDatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrizSeguimientoDatoRepository extends \Doctrine\ORM\EntityRepository
{
}
