<?php

namespace App\Entity\MatrizChiapas;

/**
 * MatrizSeguimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrizSeguimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
