<?php

namespace App\Entity\MatrizChiapas;

use Doctrine\ORM\EntityRepository;
use App\Entity\MatrizChiapas\MatrizIndicadoresRel;

/**
 * MatrizIndicadoresRelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrizIndicadoresRelRepository extends EntityRepository
{
	
}